### ISSUE TITLE
Lab 1 Feedback

### ISSUE THREAD

**Issue by alanarnholt** [STT3830-Fall2019/lab1-mohamedfa101#1]
@mohamedfa101 

Line 35 of the Rmd document has: 
## Basic Commands $ 
..it should just be :
## Basic Commands 

You do not need to include anything after the ## References in your Rmd document...the references will automatically appear from the previously created *.bib file.

The rest looks great.

**Comment by mohamedfa101** [comment]
I removed the $. Thank you
